"""JCL (Job Control Language) builder and job status model.

Provides:
  - JCLStep     — a single EXEC step (PGM= or PROC=)
  - JCLJob      — full JOB card + steps
  - JCLBuilder  — fluent builder API
  - JobStatus   — models z/OS job completion info (RC, ABEND, etc.)

The generated JCL text is standards-compliant for z/OS 2.5+.
Actual submission uses the z/OS REST API (zosmf) or FTP-to-JES2.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional


class JobClass(str, Enum):
    A = "A"; B = "B"; C = "C"; D = "D"
    E = "E"; F = "F"; G = "G"; H = "H"


class MsgClass(str, Enum):
    A = "A"; H = "H"; X = "X"


class JobCompletionCode(str, Enum):
    CC    = "CC"      # Condition code (normal)
    ABEND = "ABEND"   # Abnormal end
    JCLERR = "JCLERR" # JCL error
    FLUSH = "FLUSH"   # Step flushed
    CANCEL = "CANCEL" # Cancelled


@dataclass
class DDStatement:
    """A DD (Data Definition) statement in a JCL step."""
    dd_name: str
    dsn: Optional[str] = None          # dataset name
    disp: str = "SHR"                  # SHR | OLD | NEW | MOD
    unit: Optional[str] = None         # UNIT=SYSDA etc.
    space: Optional[str] = None        # SPACE=(CYL,(5,5))
    recfm: Optional[str] = None        # FB, VB, etc.
    lrecl: Optional[int] = None
    blksize: Optional[int] = None
    sysout: Optional[str] = None       # SYSOUT=* for output
    dcb: Optional[str] = None          # raw DCB overrides

    def render(self) -> str:
        parts: list[str] = []
        if self.sysout:
            parts.append(f"SYSOUT={self.sysout}")
        else:
            if self.dsn:
                parts.append(f"DSN={self.dsn.upper()}")
            parts.append(f"DISP={self.disp}")
            if self.unit:
                parts.append(f"UNIT={self.unit}")
            if self.space:
                parts.append(f"SPACE={self.space}")
            dcb_parts: list[str] = []
            if self.recfm:
                dcb_parts.append(f"RECFM={self.recfm}")
            if self.lrecl:
                dcb_parts.append(f"LRECL={self.lrecl}")
            if self.blksize:
                dcb_parts.append(f"BLKSIZE={self.blksize}")
            if dcb_parts:
                parts.append(f"DCB=({','.join(dcb_parts)})")
            if self.dcb:
                parts.append(self.dcb)
        return f"//{self.dd_name:<8} DD  {','.join(parts)}"


@dataclass
class JCLStep:
    """A single EXEC step in a JCL job."""
    step_name: str                           # max 8 chars, uppercase
    program: Optional[str] = None           # PGM=
    proc: Optional[str] = None             # PROC name (alternative to PGM)
    parm: Optional[str] = None             # PARM= string
    cond: str = "(0,LT)"                   # COND= on EXEC
    dd_statements: list[DDStatement] = field(default_factory=list)
    inline_comments: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.step_name = self.step_name.upper()[:8]
        if self.program:
            self.program = self.program.upper()

    def add_dd(self, dd: DDStatement) -> "JCLStep":
        self.dd_statements.append(dd)
        return self

    def render(self) -> str:
        lines: list[str] = []
        if self.inline_comments:
            for c in self.inline_comments:
                lines.append(f"//* {c}")
        exec_target = f"PGM={self.program}" if self.program else (self.proc or "IEFBR14")
        parm_part = f",PARM='{self.parm}'" if self.parm else ""
        cond_part = f",COND={self.cond}" if self.cond else ""
        lines.append(f"//{self.step_name:<8} EXEC {exec_target}{parm_part}{cond_part}")
        for dd in self.dd_statements:
            lines.append(dd.render())
        return "\n".join(lines)


@dataclass
class JCLJob:
    """A complete z/OS JCL job deck."""

    job_name: str
    account: str = "QFINTEK"
    programmer: str = "QUANTUMFINTEK"
    job_class: JobClass = JobClass.A
    msg_class: MsgClass = MsgClass.H
    msglevel: str = "(1,1)"
    notify: Optional[str] = None       # &SYSUID or specific userid
    region: str = "0M"                 # 0M = use installation default
    time: Optional[str] = None         # TIME=(0,30) = 30 seconds
    steps: list[JCLStep] = field(default_factory=list)
    prolog_comments: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.job_name = self.job_name.upper()[:8]

    def add_step(self, step: JCLStep) -> "JCLJob":
        self.steps.append(step)
        return self

    def render(self) -> str:
        lines: list[str] = []
        # Prolog comments
        lines.append(f"//* Generated by QuantumFintek zos-bridge {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")
        for c in self.prolog_comments:
            lines.append(f"//* {c}")
        # JOB card
        notify_part = f",NOTIFY={self.notify}" if self.notify else ""
        time_part   = f",TIME={self.time}" if self.time else ""
        lines.append(
            f"//{self.job_name:<8} JOB ({self.account}),"
            f"'{self.programmer[:20]}',CLASS={self.job_class.value},"
            f"MSGCLASS={self.msg_class.value},MSGLEVEL={self.msglevel},"
            f"REGION={self.region}{notify_part}{time_part}"
        )
        # Steps
        for step in self.steps:
            lines.append(step.render())
        return "\n".join(lines)


@dataclass
class JobStatus:
    """Represents the execution status of a submitted z/OS job."""

    job_id: str                          # JES2 job id, e.g. JOB12345
    job_name: str
    owner: str = ""
    status: str = "ACTIVE"              # INPUT | ACTIVE | OUTPUT | PURGED
    return_code: Optional[int] = None   # CC 0000 → 0
    abend_code: Optional[str] = None    # e.g. S0C7, U4093
    completion: Optional[JobCompletionCode] = None
    submitted_at: Optional[str] = None
    started_at: Optional[str] = None
    ended_at: Optional[str] = None
    spool_files: list[str] = field(default_factory=list)   # SYSPRINT, SYSOUT etc.

    @property
    def is_complete(self) -> bool:
        return self.status in {"OUTPUT", "PURGED"}

    @property
    def succeeded(self) -> bool:
        return (
            self.is_complete
            and self.completion == JobCompletionCode.CC
            and (self.return_code or 0) <= 4
        )

    @property
    def failed(self) -> bool:
        return self.is_complete and not self.succeeded


class JCLBuilder:
    """Fluent builder for common z/OS JCL patterns."""

    def __init__(self, job_name: str, account: str = "QFINTEK") -> None:
        self._job = JCLJob(job_name=job_name, account=account)

    def notify(self, userid: str) -> "JCLBuilder":
        self._job.notify = userid.upper()
        return self

    def comment(self, text: str) -> "JCLBuilder":
        self._job.prolog_comments.append(text)
        return self

    def step(
        self,
        name: str,
        program: Optional[str] = None,
        proc: Optional[str] = None,
        parm: Optional[str] = None,
    ) -> "_StepBuilder":
        s = JCLStep(step_name=name, program=program, proc=proc, parm=parm)
        self._job.add_step(s)
        return _StepBuilder(self, s)

    def build(self) -> JCLJob:
        return self._job

    def render(self) -> str:
        return self._job.render()


class _StepBuilder:
    def __init__(self, parent: JCLBuilder, step: JCLStep) -> None:
        self._parent = parent
        self._step = step

    def dd(self, **kwargs) -> "_StepBuilder":
        self._step.add_dd(DDStatement(**kwargs))
        return self

    def end_step(self) -> JCLBuilder:
        return self._parent
